name: Terraform CI (Plan)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.tf"
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -no-color -out=tfplan

      - name: Show plan in PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const plan = require('child_process').execSync('terraform show -no-color tfplan').toString()
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "### Terraform plan\n```\n" + plan.slice(0, 65000) + "\n```"
            })
